In [97]:
import pandas as pd
import numpy as np

In [98]:
books = pd.read_csv('books.csv')
ratings = pd.read_csv('ratings.csv')
users = pd.read_csv('users.csv')

C:\Users\DELL\AppData\Local\Temp\ipykernel_8100\835546400.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv')

In [99]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [100]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [101]:
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [102]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [103]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [104]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [105]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [106]:
books.duplicated().sum()

np.int64(0)

In [107]:
users.duplicated().sum()

np.int64(0)

In [108]:
ratings.duplicated().sum()

np.int64(0)

# Popularity Based Recommendation System

In [109]:
ratings_with_name = ratings.merge(books, on = 'ISBN')

In [110]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns = {'Book-Rating' : 'Num-Ratings'}, inplace = True)
num_rating_df

                                               Book-Title  Num-Ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [111]:
#avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
#avg_rating_df.rename(columns = {'Book-Rating' : 'avg-Ratings'}, inplace = True)
#avg_rating_df


ratings_with_name['Book-Rating'] = pd.to_numeric(ratings_with_name['Book-Rating'], errors='coerce')

avg_rating_df = ratings_with_name.groupby('Book-Title', as_index=False)['Book-Rating'].mean()
avg_rating_df.rename(columns = {'Book-Rating' : 'avg-Ratings'}, inplace = True)

avg_rating_df

                                               Book-Title  avg-Ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [112]:
popular_df = num_rating_df.merge(avg_rating_df, on = 'Book-Title')
popular_df

,Book-Title,Num-Ratings,avg-Ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [113]:
popular_df = popular_df[popular_df['Num-Ratings'] >= 250].sort_values('avg-Ratings', ascending = False).head(50)

In [114]:
popular_df= popular_df.merge(books, on = 'Book-Title').drop_duplicates('Book-Title')[['Book-Title', 'Book-Author', 'Image-URL-S', 'Image-URL-M', 'Num-Ratings', 'avg-Ratings', 'Year-Of-Publication']]

In [115]:
popular_df

,Book-Title,Book-Author,Image-URL-S,Image-URL-M,Num-Ratings,avg-Ratings,Year-Of-Publication
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,428,5.852804,1999
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,387,5.824289,2000
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,278,5.737410,1998
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,347,5.501441,2003
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,556,5.183453,2000
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...,281,5.007117,1986
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...,368,4.948370,1986
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...,575,4.895652,1999
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,http://images.amazon.com/images/P/0345339711.0...,260,4.880769,1986
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,510,4.700000,1988
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,898,4.642539,2003
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...,430,4.551163,2003
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...,449,4.545657,1991
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726,2002
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,284,4.454225,1990
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,http://images.amazon.com/images/P/0060959037.0...,253,4.450593,2001
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,http://images.amazon.com/images/P/0380789019.0...,265,4.449057,1998
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...,774,4.447028,2003
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...,283,4.356890,2002
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,493,4.354970,1997
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...,723,4.334716,1998
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,http://images.amazon.com/images/P/0671461494.0...,268,4.328358,1982
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...,335,4.289552,2002
100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,http://images.amazon.com/images/P/0385486804.0...,252,4.273810,1997
103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,http://images.amazon.com/images/P/3257208626.0...,409,4.264059,1994
116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,http://images.amazon.com/images/P/0452282152.0...,526,4.218631,2001
117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,http://images.amazon.com/images/P/0440222915.0...,283,4.173145,1996
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,http://images.amazon.com/images/P/0446672211.0...,585,4.105983,1998
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...,275,4.098182,2002
126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,http://images.amazon.com/images/P/0151008116.0...,664,4.088855,2002
130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,http://images.amazon.com/images/P/0060915544.0...,389,4.087404,1989
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,http://images.amazon.com/images/P/1558743669.0...,265,4.086792,1995
135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...,279,4.075269,1996
137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,http://images.amazon.com/images/P/0743418174.0...,490,4.055102,2002
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,http://images.amazon.com/images/P/0060938455.0...,321,4.037383,2002
140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,http://images.amazon.com/images/P/0380789035.0...,302,4.006623,2002
141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,http://images.amazon.com/images/P/0385505833.0...,322,4.006211,2001
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,http://images.amazon.com/images/P/0842329129.0...,318,4.003145,1996
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,336,4.000000,2002
157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,http://images.amazon.com/images/P/0671617028.0...,314,3.964968,1985
163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,http://images.amazon.com/images/P/0312924585.0...,256,3.960938,1991
166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,http://images.amazon.com/images/P/1573227331.0...,262,3.900763,1999
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,http://images.amazon.com/images/P/0312265840.0...,278,3.888489,2001
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...,266,3.875940,1993
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,http://images.amazon.com/images/P/0312983867.0...,269,3.825279,2003
182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,http://images.amazon.com/images/P/0316969443.0...,457,3.820569,2001
186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,http://images.amazon.com/images/P/0399501487.0...,259,3.818533,1959
192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...,413,3.796610,1990
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...,301,3.777409,1986
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...,356,3.772472,2000

# Collaborative Filtering Based Recommendation System

In [116]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
plu = x[x].index

In [117]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(plu)]

In [118]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books = y[y].index

In [119]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [120]:
pt = final_ratings.pivot_table(index = 'Book-Title', columns = 'User-ID', values = 'Book-Rating')

In [121]:
pt.fillna(0, inplace=True)

In [122]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [123]:
from sklearn.metrics.pairwise import cosine_similarity

In [124]:
similarity_score = cosine_similarity(pt)

In [125]:
similarity_score.shape

(706, 706)

In [129]:
def recommend(book_name):
    index = np.where(pt.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])), key=lambda x: x[1], reverse=True)[1:6]

    data = []
    for i in similar_items:
        item = []
        temp_df = popular_df[popular_df['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        #item.extend(list(temp_df.drop_duplicates('Book-Title')['num-ratings'].values))
        #item.extend(list(temp_df.drop_duplicates('Book-Title')['avg-Ratings'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Year-Of-Publication'].values))

        data.append(item)
        print(temp_df.columns)

    return data

In [130]:
recommend('Saving Faith')

Index(['Book-Title', 'Book-Author', 'Image-URL-S', 'Image-URL-M',
       'Num-Ratings', 'avg-Ratings', 'Year-Of-Publication'],
      dtype='object')
Index(['Book-Title', 'Book-Author', 'Image-URL-S', 'Image-URL-M',
       'Num-Ratings', 'avg-Ratings', 'Year-Of-Publication'],
      dtype='object')
Index(['Book-Title', 'Book-Author', 'Image-URL-S', 'Image-URL-M',
       'Num-Ratings', 'avg-Ratings', 'Year-Of-Publication'],
      dtype='object')
Index(['Book-Title', 'Book-Author', 'Image-URL-S', 'Image-URL-M',
       'Num-Ratings', 'avg-Ratings', 'Year-Of-Publication'],
      dtype='object')
Index(['Book-Title', 'Book-Author', 'Image-URL-S', 'Image-URL-M',
       'Num-Ratings', 'avg-Ratings', 'Year-Of-Publication'],
      dtype='object')

[[], [], [], [], []]

In [128]:
pt.index[545]

"The Handmaid's Tale"

In [75]:
import pickle
pickle.dump(popular_df, open('popular.pkl', 'wb'))

In [82]:
pickle.dump(pt, open('pt.pkl', 'wb'))
pickle.dump(books, open('books.pkl', 'wb'))
pickle.dump(similarity_score, open('similarity_score.pkl', 'wb'))

In [91]:
print(temp_df.columns)

NameError: name 'temp_df' is not defined